# Generated by Django 4.0.1 on 2022-08-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('TECH', 'Technology'), ('SPRT', 'Sports'), ('LIFE', 'Lifestyle')], default='TECH', max_length=4),
        ),
    ]
